<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2QDwxZW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2QDwxZW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2QDwxZW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2QDwxZW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2QDwxZW\App_KernelDevDebugContainer([
    'container.build_hash' => '2QDwxZW',
    'container.build_id' => '1a81a48e',
    'container.build_time' => 1635787088,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2QDwxZW');
